/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesTabooRouteImport } from './routes/games.taboo'
import { Route as GamesScorekeeperRouteImport } from './routes/games.scorekeeper'
import { Route as GamesLetterBridgeRouteImport } from './routes/games.letter-bridge'
import { Route as GamesCodenamesRouteImport } from './routes/games.codenames'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTabooRoute = GamesTabooRouteImport.update({
  id: '/games/taboo',
  path: '/games/taboo',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesScorekeeperRoute = GamesScorekeeperRouteImport.update({
  id: '/games/scorekeeper',
  path: '/games/scorekeeper',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesLetterBridgeRoute = GamesLetterBridgeRouteImport.update({
  id: '/games/letter-bridge',
  path: '/games/letter-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCodenamesRoute = GamesCodenamesRouteImport.update({
  id: '/games/codenames',
  path: '/games/codenames',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/codenames': typeof GamesCodenamesRoute
  '/games/letter-bridge': typeof GamesLetterBridgeRoute
  '/games/scorekeeper': typeof GamesScorekeeperRoute
  '/games/taboo': typeof GamesTabooRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games/codenames': typeof GamesCodenamesRoute
  '/games/letter-bridge': typeof GamesLetterBridgeRoute
  '/games/scorekeeper': typeof GamesScorekeeperRoute
  '/games/taboo': typeof GamesTabooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/codenames': typeof GamesCodenamesRoute
  '/games/letter-bridge': typeof GamesLetterBridgeRoute
  '/games/scorekeeper': typeof GamesScorekeeperRoute
  '/games/taboo': typeof GamesTabooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games/codenames'
    | '/games/letter-bridge'
    | '/games/scorekeeper'
    | '/games/taboo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games/codenames'
    | '/games/letter-bridge'
    | '/games/scorekeeper'
    | '/games/taboo'
  id:
    | '__root__'
    | '/'
    | '/games/codenames'
    | '/games/letter-bridge'
    | '/games/scorekeeper'
    | '/games/taboo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesCodenamesRoute: typeof GamesCodenamesRoute
  GamesLetterBridgeRoute: typeof GamesLetterBridgeRoute
  GamesScorekeeperRoute: typeof GamesScorekeeperRoute
  GamesTabooRoute: typeof GamesTabooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/taboo': {
      id: '/games/taboo'
      path: '/games/taboo'
      fullPath: '/games/taboo'
      preLoaderRoute: typeof GamesTabooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/scorekeeper': {
      id: '/games/scorekeeper'
      path: '/games/scorekeeper'
      fullPath: '/games/scorekeeper'
      preLoaderRoute: typeof GamesScorekeeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/letter-bridge': {
      id: '/games/letter-bridge'
      path: '/games/letter-bridge'
      fullPath: '/games/letter-bridge'
      preLoaderRoute: typeof GamesLetterBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/codenames': {
      id: '/games/codenames'
      path: '/games/codenames'
      fullPath: '/games/codenames'
      preLoaderRoute: typeof GamesCodenamesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesCodenamesRoute: GamesCodenamesRoute,
  GamesLetterBridgeRoute: GamesLetterBridgeRoute,
  GamesScorekeeperRoute: GamesScorekeeperRoute,
  GamesTabooRoute: GamesTabooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
