export type TabooCard = {
  word: string;
  taboo: [string, string, string, string, string];
};

export const TABOO_CARDS: TabooCard[] = [
  {
    word: "AIRPORT",
    taboo: ["PLANE", "FLIGHT", "TERMINAL", "TRAVEL", "RUNWAY"],
  },
  {
    word: "ALLIGATOR",
    taboo: ["CROCODILE", "REPTILE", "SWAMP", "TEETH", "GREEN"],
  },
  { word: "ANCHOR", taboo: ["SHIP", "BOAT", "OCEAN", "DROP", "CHAIN"] },
  {
    word: "APPLAUSE",
    taboo: ["CLAP", "AUDIENCE", "CHEER", "HANDS", "PERFORMANCE"],
  },
  { word: "ASTRONAUT", taboo: ["SPACE", "MOON", "NASA", "ROCKET", "SUIT"] },
  { word: "BACKPACK", taboo: ["BAG", "SCHOOL", "SHOULDER", "ZIPPER", "CARRY"] },
  { word: "BALLOON", taboo: ["HELIUM", "AIR", "PARTY", "FLOAT", "POP"] },
  { word: "BANK", taboo: ["MONEY", "ACCOUNT", "CASH", "DEPOSIT", "WITHDRAW"] },
  {
    word: "BARBECUE",
    taboo: ["GRILL", "COOKOUT", "MEAT", "CHARCOAL", "SMOKE"],
  },
  { word: "BASKETBALL", taboo: ["HOOP", "DRIBBLE", "COURT", "NBA", "BALL"] },
  {
    word: "BATTERY",
    taboo: ["POWER", "CHARGE", "PHONE", "ELECTRIC", "ENERGY"],
  },
  { word: "BEARD", taboo: ["FACE", "HAIR", "MAN", "SHAVE", "MUSTACHE"] },
  { word: "BIRTHDAY", taboo: ["CAKE", "CANDLE", "PARTY", "PRESENT", "AGE"] },
  { word: "BLANKET", taboo: ["BED", "WARM", "COVER", "SLEEP", "COZY"] },
  {
    word: "BLUEPRINT",
    taboo: ["PLAN", "ARCHITECT", "BUILDING", "DRAWING", "DESIGN"],
  },
  {
    word: "BRAINSTORM",
    taboo: ["IDEA", "THINK", "MEETING", "CREATIVE", "GROUP"],
  },
  { word: "BRIDGE", taboo: ["RIVER", "CROSS", "ROAD", "WATER", "STRUCTURE"] },
  { word: "BROCCOLI", taboo: ["VEGETABLE", "GREEN", "TREE", "EAT", "STEM"] },
  {
    word: "BROWSER",
    taboo: ["INTERNET", "WEBSITE", "CHROME", "FIREFOX", "SEARCH"],
  },
  { word: "CAMPFIRE", taboo: ["OUTDOOR", "FIRE", "WOOD", "SMORES", "CAMP"] },
  { word: "CARPET", taboo: ["FLOOR", "RUG", "VACUUM", "ROOM", "SOFT"] },
  { word: "CASTLE", taboo: ["KING", "QUEEN", "TOWER", "MEDIEVAL", "FORTRESS"] },
  {
    word: "CATERPILLAR",
    taboo: ["BUTTERFLY", "INSECT", "COCOON", "LEAF", "WORM"],
  },
  { word: "CHEF", taboo: ["COOK", "KITCHEN", "RESTAURANT", "FOOD", "HAT"] },
  { word: "CHESTNUT", taboo: ["TREE", "NUT", "ROAST", "BROWN", "SHELL"] },
  { word: "CHIMNEY", taboo: ["FIREPLACE", "SMOKE", "ROOF", "HOUSE", "SANTA"] },
  { word: "CHOCOLATE", taboo: ["CANDY", "SWEET", "COCOA", "BAR", "DESSERT"] },
  { word: "CIRCUS", taboo: ["CLOWN", "TENT", "ACROBAT", "ANIMAL", "SHOW"] },
  { word: "COCONUT", taboo: ["TROPICAL", "PALM", "SHELL", "MILK", "ISLAND"] },
  {
    word: "COMPASS",
    taboo: ["NORTH", "DIRECTION", "MAP", "NAVIGATE", "SOUTH"],
  },
  { word: "CONCERT", taboo: ["MUSIC", "BAND", "LIVE", "STAGE", "CROWD"] },
  {
    word: "COOKIE",
    taboo: ["BAKE", "CHOCOLATE", "DESSERT", "SWEET", "CRUMBS"],
  },
  {
    word: "CORRIDOR",
    taboo: ["HALLWAY", "BUILDING", "WALK", "DOOR", "PASSAGE"],
  },
  { word: "CROWN", taboo: ["KING", "QUEEN", "HEAD", "JEWEL", "ROYAL"] },
  { word: "DENTIST", taboo: ["TEETH", "DRILL", "DOCTOR", "MOUTH", "CAVITY"] },
  { word: "DESERT", taboo: ["SAND", "DRY", "HOT", "CACTUS", "DUNES"] },
  { word: "DIAMOND", taboo: ["RING", "JEWEL", "SPARKLE", "ENGAGEMENT", "GEM"] },
  {
    word: "DINOSAUR",
    taboo: ["PREHISTORIC", "FOSSIL", "EXTINCT", "REX", "GIANT"],
  },
  {
    word: "DOLPHIN",
    taboo: ["OCEAN", "WHALE", "SWIM", "MAMMAL", "INTELLIGENT"],
  },
  { word: "DOORBELL", taboo: ["RING", "DOOR", "HOUSE", "BUTTON", "VISITOR"] },
  { word: "DRAGON", taboo: ["FIRE", "MYTH", "WINGS", "SCALES", "MONSTER"] },
  { word: "ECLIPSE", taboo: ["SUN", "MOON", "SHADOW", "SKY", "SOLAR"] },
  { word: "ELEVATOR", taboo: ["LIFT", "FLOOR", "BUTTON", "BUILDING", "UP"] },
  {
    word: "ESPRESSO",
    taboo: ["COFFEE", "SHOT", "CAFFEINE", "MACHINE", "BEAN"],
  },
  { word: "FARMER", taboo: ["CROP", "TRACTOR", "FIELD", "BARN", "HARVEST"] },
  { word: "FEATHER", taboo: ["BIRD", "WING", "LIGHT", "SOFT", "PLUME"] },
  { word: "FIREWORK", taboo: ["EXPLODE", "SKY", "JULY", "SPARK", "COLOR"] },
  { word: "FISHBOWL", taboo: ["FISH", "WATER", "GLASS", "PET", "TANK"] },
  { word: "FOOTPRINT", taboo: ["SHOE", "TRACK", "GROUND", "STEP", "MARK"] },
  { word: "GALAXY", taboo: ["SPACE", "STARS", "MILKY", "UNIVERSE", "PLANET"] },
  { word: "GARAGE", taboo: ["CAR", "HOUSE", "DOOR", "PARK", "DRIVEWAY"] },
  { word: "GIRAFFE", taboo: ["LONG", "NECK", "ANIMAL", "SPOTS", "AFRICA"] },
  { word: "GLACIER", taboo: ["ICE", "MOUNTAIN", "COLD", "MELT", "ARCTIC"] },
  { word: "GUITAR", taboo: ["STRING", "MUSIC", "PLAY", "BAND", "INSTRUMENT"] },
  { word: "HAMBURGER", taboo: ["BUN", "BEEF", "FAST", "FOOD", "PATTY"] },
  { word: "HEADPHONES", taboo: ["MUSIC", "EARS", "LISTEN", "SOUND", "AUDIO"] },
  {
    word: "HELICOPTER",
    taboo: ["FLY", "ROTOR", "BLADES", "AIRCRAFT", "PILOT"],
  },
  {
    word: "HONEYMOON",
    taboo: ["WEDDING", "TRIP", "NEWLYWED", "ROMANTIC", "VACATION"],
  },
  {
    word: "HOSPITAL",
    taboo: ["DOCTOR", "NURSE", "PATIENT", "EMERGENCY", "MEDICAL"],
  },
  { word: "ICEBERG", taboo: ["ICE", "OCEAN", "TITANIC", "FLOAT", "GLACIER"] },
  {
    word: "JELLYFISH",
    taboo: ["OCEAN", "STING", "TENTACLE", "TRANSPARENT", "SEA"],
  },
  {
    word: "JOURNALIST",
    taboo: ["NEWS", "REPORTER", "ARTICLE", "PAPER", "INTERVIEW"],
  },
  { word: "KEYBOARD", taboo: ["TYPE", "COMPUTER", "KEYS", "LETTERS", "MOUSE"] },
  { word: "KITE", taboo: ["FLY", "STRING", "WIND", "SKY", "PAPER"] },
  { word: "LABYRINTH", taboo: ["MAZE", "PATH", "CONFUSING", "EXIT", "PUZZLE"] },
  { word: "LANTERN", taboo: ["LIGHT", "CAMPING", "CANDLE", "GLOW", "HANG"] },
  { word: "LAVENDER", taboo: ["PURPLE", "FLOWER", "SCENT", "PLANT", "SOAP"] },
  { word: "LIGHTHOUSE", taboo: ["OCEAN", "BEACON", "SHORE", "SHIP", "TOWER"] },
  { word: "LOCKSMITH", taboo: ["KEY", "DOOR", "LOCK", "OPEN", "SECURITY"] },
  { word: "MAGNET", taboo: ["METAL", "STICK", "ATTRACT", "POLE", "FRIDGE"] },
  { word: "MARATHON", taboo: ["RUN", "RACE", "MILES", "ENDURANCE", "42"] },
  { word: "MICROSCOPE", taboo: ["SCIENCE", "LOOK", "SMALL", "LAB", "LENS"] },
  { word: "MOSAIC", taboo: ["TILE", "ART", "PATTERN", "PIECES", "IMAGE"] },
  { word: "MOUNTAINEER", taboo: ["CLIMB", "PEAK", "ROPE", "SUMMIT", "ALPINE"] },
  { word: "MOUSTACHE", taboo: ["HAIR", "FACE", "LIP", "BEARD", "SHAVE"] },
  { word: "NECKLACE", taboo: ["JEWELRY", "CHAIN", "NECK", "PENDANT", "WEAR"] },
  { word: "NOTEBOOK", taboo: ["PAPER", "WRITE", "PAGES", "SCHOOL", "NOTES"] },
  { word: "OASIS", taboo: ["DESERT", "WATER", "PALM", "SPRING", "DRY"] },
  {
    word: "ORCHESTRA",
    taboo: ["MUSIC", "CONDUCTOR", "VIOLIN", "SYMPHONY", "INSTRUMENT"],
  },
  { word: "OUTLET", taboo: ["PLUG", "ELECTRIC", "WALL", "POWER", "SOCKET"] },
  { word: "PALACE", taboo: ["KING", "QUEEN", "ROYAL", "CASTLE", "RESIDENCE"] },
  { word: "PARACHUTE", taboo: ["SKY", "JUMP", "FALL", "CANOPY", "SAFETY"] },
  { word: "PEACOCK", taboo: ["BIRD", "FEATHERS", "TAIL", "COLORFUL", "PROUD"] },
  {
    word: "PENGUIN",
    taboo: ["BIRD", "ANTARCTICA", "BLACK", "WHITE", "WADDLE"],
  },
  { word: "PIRATE", taboo: ["SHIP", "TREASURE", "CAPTAIN", "EYE", "HOOK"] },
  { word: "PLANET", taboo: ["SPACE", "EARTH", "ORBIT", "SUN", "WORLD"] },
  {
    word: "POPCORN",
    taboo: ["MOVIE", "KERNEL", "BUTTER", "SNACK", "MICROWAVE"],
  },
  { word: "POSTCARD", taboo: ["MAIL", "TRAVEL", "STAMP", "PICTURE", "SEND"] },
  { word: "PUMPKIN", taboo: ["ORANGE", "HALLOWEEN", "PIE", "SQUASH", "CARVE"] },
  {
    word: "PYRAMID",
    taboo: ["EGYPT", "TRIANGLE", "PHARAOH", "DESERT", "TOMB"],
  },
  { word: "RAINBOW", taboo: ["COLORS", "RAIN", "SKY", "ARC", "PRISM"] },
  { word: "REFEREE", taboo: ["WHISTLE", "SPORT", "RULE", "FOUL", "OFFICIAL"] },
  { word: "ROBOT", taboo: ["MACHINE", "METAL", "AI", "AUTOMATIC", "ANDROID"] },
  { word: "SAILBOAT", taboo: ["WATER", "WIND", "SAIL", "OCEAN", "BOAT"] },
  { word: "SATELLITE", taboo: ["SPACE", "ORBIT", "EARTH", "SIGNAL", "DISH"] },
  { word: "SCARECROW", taboo: ["FARM", "CROW", "FIELD", "STRAW", "BIRD"] },
  { word: "SCISSORS", taboo: ["CUT", "PAPER", "BLADES", "ROCK", "TOOL"] },
  { word: "SEAHORSE", taboo: ["OCEAN", "FISH", "TAIL", "ANIMAL", "REEF"] },
  { word: "SHADOW", taboo: ["LIGHT", "DARK", "SUN", "SILHOUETTE", "GROUND"] },
  {
    word: "SKYSCRAPER",
    taboo: ["TALL", "BUILDING", "CITY", "FLOORS", "TOWER"],
  },
  { word: "SNOWMAN", taboo: ["SNOW", "WINTER", "CARROT", "COLD", "FROSTY"] },
  { word: "SPONGE", taboo: ["WATER", "CLEAN", "YELLOW", "SOAP", "ABSORB"] },
  {
    word: "STETHOSCOPE",
    taboo: ["DOCTOR", "HEART", "CHEST", "NURSE", "LISTEN"],
  },
  {
    word: "SUBMARINE",
    taboo: ["UNDERWATER", "NAVY", "OCEAN", "VESSEL", "PERISCOPE"],
  },
  { word: "SUNSCREEN", taboo: ["SUN", "SPF", "SKIN", "BEACH", "LOTION"] },
  { word: "TELESCOPE", taboo: ["STARS", "LOOK", "SPACE", "LENS", "OBSERVE"] },
  {
    word: "THERMOMETER",
    taboo: ["TEMPERATURE", "FEVER", "DEGREES", "HEAT", "MEASURE"],
  },
  { word: "THUNDER", taboo: ["LIGHTNING", "STORM", "LOUD", "SKY", "RAIN"] },
  {
    word: "TOOTHBRUSH",
    taboo: ["TEETH", "PASTE", "MOUTH", "BATHROOM", "BRUSH"],
  },
  { word: "TORNADO", taboo: ["WIND", "STORM", "FUNNEL", "TWISTER", "SPIN"] },
  { word: "TRAFFIC", taboo: ["CARS", "ROAD", "JAM", "DRIVE", "CONGESTION"] },
  { word: "UMBRELLA", taboo: ["RAIN", "WET", "OPEN", "COVER", "STORM"] },
  { word: "VACUUM", taboo: ["CLEAN", "FLOOR", "DUST", "SUCTION", "HOUSE"] },
  { word: "VOLCANO", taboo: ["LAVA", "ERUPTION", "MOUNTAIN", "ASH", "MAGMA"] },
  { word: "WALLET", taboo: ["MONEY", "CASH", "POCKET", "CARDS", "LEATHER"] },
  { word: "WATERFALL", taboo: ["RIVER", "DROP", "CLIFF", "NATURE", "CASCADE"] },
  { word: "WHISTLE", taboo: ["BLOW", "SOUND", "REFEREE", "LIPS", "TUNE"] },
  { word: "WINDMILL", taboo: ["WIND", "TURBINE", "BLADES", "DUTCH", "POWER"] },
  { word: "ZIPPER", taboo: ["JACKET", "PANTS", "UP", "TEETH", "CLOSE"] },
];
